### PR TITLE
fix(explorer): improve tab styling with segmented control

### LINKED ISSUE #226: [Explorer] Improve Tab styling
The styling for the tab navigation buttons on the instrumentation detail page could use some attention.

It seems like there is unnecessary margin between the tab bottom and the tab content section, and maybe there shouldn't be a glow / shadow on the bottom either. Whoever works on this can also feel free to propose something entirely new or different in how we style these.

Current view:

Image

### PR DESCRIPTION
**Pull request by Vjc5h3nt**
## Summary
- Replaces the default tab navigation with a segmented control featuring a sliding pill indicator on both the instrumentation detail page and configuration builder page
- Removes the unwanted glow/shadow on the active tab and unnecessary margin between tabs and content
- Active tab uses an amber highlight with smooth 300ms sliding animation between tabs

Closes #226

## Test plan
- [x] All 366 JS tests pass (`bun run test`)
- [x] TypeScript typecheck passes (`bun run typecheck`)
- [x] ESLint passes (`bun run lint`)
- [x] Prettier passes on changed files (`bun run format:check`)
- [x] Copyright headers valid
- [x] Verified instrumentation detail page tabs (Details, Telemetry, Configuration) render correctly
- [x] Verified configuration builder page tabs (SDK, Instrumentation) render correctly
- [x] Sliding pill animates smoothly between tabs
- [x] Keyboard navigation works (arrow keys between tabs)

### CODE REVIEW

**Comment by Vjc5h3nt** [comment]
Hi @jaydeluca, let me know if the proposed tab design in this PR works for you. Also curious ,  is it possible to test the PR screenshot feature (#247) here by adding the \`add-screenshots\` label?"

**Comment by jaydeluca** [comment]
@Vjc5h3nt the new tabs look great! I love it! 

It seems like the `add-screenshots` automation might not be working, i added the label but am not seeing the action kick off, we might need to investigate

File: ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        className="absolute top-1 bottom-1 rounded-lg"
+        aria-hidden="true"
+        style={{
+          left: pillStyle.left,
+          width: pillStyle.width,
+          background: "oklch(0.78 0.16 75 / 0.12)",
+          border: "1px solid oklch(0.78 0.16 75 / 0.4)",
+          transition:
+            "left 300ms cubic-bezier(0.22, 1, 0.36, 1), width 300ms cubic-bezier(0.22, 1, 0.36, 1)",
+        }}
```
[the remark this answers is not in the document]
Comment (jaydeluca) [reply ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx:71]: a tip is to tell your agent to reference the `DESIGN.md` doc and it might be able to help here

**Comment by Vjc5h3nt** [comment]
Taken care of the above mentioned feedback. The PR screenshots failure is expected and will be resolved in PR #266

**Comment by jaydeluca** [comment]
i think adding the triggers fixed part of it. The latest error is now:

```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/fix/improve-tab-styling-226
  /usr/bin/git tag --list fix/improve-tab-styling-226
  Error: A branch or tag with the name 'fix/improve-tab-styling-226' could not be found
```

I think we can remove [these lines](https://github.com/open-telemetry/opentelemetry-ecosystem-explorer/blob/main/.github/workflows/screenshots.yml#L27-L29)

**Comment by jaydeluca** [comment]
actually, instead of removing those lines, we might need to fix the ref and update it to ` ref: ${{ github.event.pull_request.head.ref }}`

Would you mind running through a full test in your fork?

**Comment by Vjc5h3nt** [comment]
@jaydeluca, I've tested the ref fix (github.head_ref → github.event.pull_request.head.ref) in my fork with a same-repo PR and it's working - https://github.com/Vjc5h3nt/opentelemetry-ecosystem-explorer/pull/3, Is this what you are expecting? For cross-fork testing, the fix would need to be on upstream main first since GitHub runs pull_request workflows from the base branch. Would you like to merge this and re-test with the add-screenshots label on a fork PR, or should I try to set up a cross-fork test beforehand?  
 
Also, would you prefer to keep the screenshot workflow fix in this PR or split it out into a separate one so the tab styling changes stay focused?

**Comment by jaydeluca** [comment]
> Would you like to merge this and re-test with the add-screenshots label on a fork PR, or should I try to set up a cross-fork test beforehand?

Can you add the change in a separate PR and we can merge it and re-test with this PR before we merge this one? It's a great test example. You can just do the ref change, no need to do any additional cross-fork updates

File: ecosystem-explorer/src/components/ui/segmented-tabs.tsx [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+import { useState, useRef, useLayoutEffect, useCallback, useEffect, type JSX } from "react";
+import * as RadixTabs from "@radix-ui/react-tabs";
+
```
Comment (jaydeluca) [inline ecosystem-explorer/src/components/ui/segmented-tabs.tsx:18]: so the existing `TabsList` and `TabsTrigger` are completely unused now, so we should be able to remove that code and the associated `tabs.test.tsx` tests? unless we can just move this code into those existing classes and repurpose the tests. I do think this tab component is better suited for the [generic ui](https://github.com/open-telemetry/opentelemetry-ecosystem-explorer/tree/main/ecosystem-explorer/src/components/ui) folder instead of being scoped to just the javaagent

File: ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+      {tabs.map((tab) => (
+        <RadixTabs.Trigger
+          key={tab.value}
+          value={tab.value}
+          ref={(el) => {
+            buttonRefs.current[tab.value] = el;
+          }}
+          className={`relative z-10 inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors duration-200 ${
+            value === tab.value ? "text-primary" : "text-muted-foreground hover:text-foreground"
+          }`}
```
Comment (jaydeluca) [inline ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx]: Radix exposes data-state="active" | "inactive" that we can use instead of conditionals

```suggestion
          className={`relative z-10 inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors duration-200 data-[state=active]:text-primary data-[state=inactive]:text-muted-foreground`}
```

File: ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+import { useState, useRef, useLayoutEffect, useCallback, useEffect, type JSX } from "react";
+import * as RadixTabs from "@radix-ui/react-tabs";
+
+interface TabItem {
+  value: string;
+  label: string;
+  icon?: JSX.Element;
```
Comment (jaydeluca) [inline ecosystem-explorer/src/features/java-agent/components/segmented-tabs.tsx]: `JSX.Element` rejects fragments, strings, and conditional `null` icons. `ReactNode` is the conventional type for "anything renderable" and is what every other prop in this codebase that takes optional UI uses. 

After we update this, `{tab.icon && tab.icon}` on line 85 can be simplified to `{tab.icon}` since React already handles `undefined`/`null`/`false` children.


```suggestion
  icon?: ReactNode;
```

**Review by jaydeluca — COMMENTED** [review]
looks great, left some comments about location of the component and some other small changes. If you could also get a basic test or two wired up that would be great. 

As a side note, the screenshot automation isn't working, but i believe it has to do with permissions and I will need to rethink how we go about it, we we can ignore that part for now. Thanks for your help there!

**Review by jaydeluca — APPROVED** [review]
this looks so much better, thanks!

File: ecosystem-explorer/src/components/ui/segmented-tabs.tsx (hunk 2 above)
Comment (Vjc5h3nt) [reply ecosystem-explorer/src/components/ui/segmented-tabs.tsx:18]: Removed the unused TabsList and TabsTrigger from tabs.tsx , the only exports left are Tabs and TabsContent. 

Kept tabs.test.tsx with minimal tests for TabsContent, and added a seperate segmented-tabs.test.tsx with tests covering roles, tab switching, data-state attributes, keyboard nav, and icon rendering.
